pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                bat 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
            }
            stage('Deploy in staging Env'){
            steps {
                build job :'Deploy_App_Staging_Env'
            }
            
        }
            stage('Deploy in production Env'){
            steps {
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
               
            }
             build job :'Deploy_App_Production_Env'
       
    }
}
    }
}